### ISSUE TITLE
Qflow migration step  run fail in ubuntu

### ISSUE THREAD

**Issue by zeropower** [RTimothyEdwards/qflow#1]
![qflow](https://user-images.githubusercontent.com/20761964/63663158-e1283600-c7f3-11e9-81d6-4508a97270b7.PNG)
Device Information:
OS: Ubuntu 18.04LTS run in VirtualBox
qflow version: 1.3 (1.4 also has the same problem)
When I run qflow migration step , the error message is raised.
What did I miss?  Can you give me some advice?

**Comment by RTimothyEdwards** [comment]
You are using magic version 8.0.  This has long been deprecated.  Get magic version 8.2 from my github repo.  All tools used with qflow should be from my github repos, or you will likely have compatibility problems.

Regards,
Tim

**Comment by zeropower** [comment]
Qflow is running normally. Thank you.
