### ISSUE TITLE
No timing analysis from vesta when using sky130 pdk

### ISSUE THREAD

**Issue by SweeperAA** [RTimothyEdwards/qflow#14]
Output from vesta: 
Sorry, only know how to handle table lookup!
Parsing library ""sky130_fd_sc_hs__ff_n40C_1v95""

**Comment by RTimothyEdwards** [comment]
I have not had the time to debug this.  I'm pretty sure the SkyWater liberty files use table lookup, so there's a parsing problem somewhere.

**Comment by RTimothyEdwards** [comment]
I finally got around to fixing this earlier this week.  It should be good to go now.
