### ISSUE TITLE
Incorrect def output by vlog2Def when using RePlAce as the placement tool

### ISSUE THREAD

**Issue by arun13e** [RTimothyEdwards/qflow#4]
I am using qflow 1.4.74 with osu035 and memory files generated by OpenRAM as hard macros, everything went smoothly with synthesis but while using RePlAce as a placement tool, RePlAce outputs `** ERROR:  Pin Instance ( dout0 ) does not exist in MACRO statement (lefPinMapStor) ` , found out that dout0 is a bus and is the output for memory macro generated by OpenRAM, vlog2def is placing buses instead of `dout0[0], dout0[1]` in the netlist part of the DEF file generated, while designs without buses seems to work fine.

**Comment by RTimothyEdwards** [comment]
It does sound like vlog2def needs fixing.  Can you please make a tarball example with files and send it to me at tim@opencircuitdesign.com?

**Comment by arun13e** [comment]
sure

**Comment by RTimothyEdwards** [comment]
I'm going to close this issue as it has been resolved, although I'm sure there are plenty of other problems with using hard macros and/or using RePlAce, both of which have been only lightly tested in qflow.
